### ISSUE TITLE
Placeholder content still in place.

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Ledawi-Roofs-Site#8]
![screenshot from 2017-03-23 17-38-51](https://cloud.githubusercontent.com/assets/20294485/24255981/aa185dde-0fef-11e7-990e-bd1a7aa43071.png)
![screenshot from 2017-03-23 17-39-10](https://cloud.githubusercontent.com/assets/20294485/24255982/aa1ba700-0fef-11e7-80bb-3e533afec5a2.png)
Some things are still "lorem ipsum". What do we do with these?

**Comment by MeanEYE** [comment]
@talovdat this issue is still probably present but it's content only. So not my issue.

**Comment by talovdat** [comment]
Closing issue due to a violation of payment contract.
